FROM node:16-alpine AS dev

WORKDIR /app
RUN chown node:node /app
USER node
CMD ["yarn", "dev"]

FROM dev AS build

COPY --chown=node:node ./package*.json ./
COPY --chown=node:node ./yarn.lock ./
RUN yarn
COPY ./ ./

RUN yarn build

FROM node:16-alpine AS production

USER node
WORKDIR /app
COPY --from=BUILD /app/.output/  ./
CMD ["node", "./server/index.mjs"]
