FROM node:16-alpine AS dev

USER node
WORKDIR /app
CMD ["yarn", "dev"]

FROM dev AS build

COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY ./ ./

RUN yarn build

FROM node:16-alpine AS production

USER node
WORKDIR /app
COPY --from=BUILD /app/.output/  ./
CMD ["node", "./server/index.mjs"]
