FROM node:16-alpine AS dev

USER node
WORKDIR /api
CMD ["yarn", "start:dev"]

FROM dev as BUILD

COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY ./ ./
RUN yarn build
RUN NODE_ENV=production yarn

FROM node:16-alpine AS production

USER node
WORKDIR /api
COPY --from=BUILD /api/dist/ ./
COPY --from=BUILD /api/node_modules ./node_modules
CMD ["node", "./main.js"]
