FROM node:16-alpine AS dev

USER node
WORKDIR /api
CMD ["yarn", "start:dev"]

FROM dev as BUILD

RUN yarn build
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN NODE_ENV=production yarn install
COPY ./ ./

FROM node:16-alpine AS production

USER node
WORKDIR /api
COPY --from=BUILD /api/dist/ ./
COPY --from=BUILD /api/node_modules ./node_modules
CMD ["node", "./main.js"]
