FROM node:16-alpine AS dev

USER node
WORKDIR /app
COPY ./package*.json ./
COPY ./yarn.lock ./
RUN yarn
COPY ./ ./
CMD ["yarn", "start:dev"]

FROM dev as BUILD

RUN yarn build
RUN NODE_ENV=production yarn install

FROM node:16-alpine AS production

USER node
WORKDIR /app
COPY --from=BUILD /app/dist/ ./
COPY --from=BUILD /app/node_modules ./node_modules
CMD ["node", "./main.js"]
